# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Week09_Practice' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Week09_Practice
pod 'Alamofire'
pod 'SwiftyJSON', '~> 4.0'
end
