# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'week5_practice' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for week5_practice
  pod 'lottie-ios'
  pod 'SnapKit'

end
