# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LoginSampleNaver' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for LoginSampleNaver
pod 'naveridlogin-sdk-ios'
pod 'Alamofire', '~> 5.1'
  target 'LoginSampleNaverTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'LoginSampleNaverUITests' do
    # Pods for testing
  end

end
