# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'UMC_fifthweekmission' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for UMC_fifthweekmission
  pod 'JGProgressHUD'
  pod 'lottie-ios'

  target 'UMC_fifthweekmissionTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'UMC_fifthweekmissionUITests' do
    # Pods for testing
  end

end
