# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Week05_Mission' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Week05_Mission
	pod 'lottie-ios'
  target 'Week05_MissionTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Week05_MissionUITests' do
    # Pods for testing
  end

end
