# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LoginSample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for LoginSample
pod 'FirebaseAuth'
pod 'FirebaseFirestore'
pod 'GoogleSignIn' 
pod 'naveridlogin-sdk-ios'
pod 'Alamofire', '~> 5.1'
target 'LoginSampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'LoginSampleUITests' do
    # Pods for testing
  end

end
